server:
  port: 8080
  use-forward-headers: true  

aggregator:
  context:
    path: "/aggregator"
  dictionary:
    name: Sample Description
    services:
      - id: "first-service"
      - id: "second-service"
        description: "Test Description"